---
# tasks file for nginx_role
- name: install nginx
  apt: name=nginx state=latest
  tags: install_nginx

- name: copy index.html template
  template:
    src: index.html
    dest: /var/www/html
  notify: restart nginx
  tags: copy_file

- name: enable and start service
  service:
    name: nginx
    enabled: yes
    state: started
  tags: enable_nginx
