---

- hosts: first
  become: true
  pre_tasks: #run before anything else is run

  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
  
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: first
  become: true
  tasks:

  - name: install unzip
    tags: workstation
    package:
      name: unzip
  
  # - name: install prometheus
  #   tags: workstation
  #   unarchive:
  #     src: https://github.com/prometheus/prometheus/releases/download/v2.44.0/prometheus-2.44.0.windows-amd64.zip
  #     dest: /usr/local/bin
  #     remote_src: yes
  #     mode: 0755
  #     owner: root
  #     group: root
  
  - name: Delete file
    tags: delete
    file:
      state: absent
      path: /usr/local/bin/prometheus-2.44.0.windows-amd64

- hosts: first
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd,start_httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: apache,centos,httpd,change_file
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd,change_file
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCowQlNaxhu0cPHxIiQwt0WYWKyuy9oW1Zxav8cZRfHo2snYmXTwWbmeFmyyQ65mPLdFoWHgTcZmHzSltpid9HTqYHuw7V9D0uRGaxAdVEH3Np6UnchqzjgmOb/j5bAjtkBOKKbgkDMKZyMdcgJvvPba+ctGS4tDQOpKU/HGYwfVugGcfzo1M9XbBaNFcbc+IZ6/ByWy/PibS7S1H242wVy+sWu0fh2nJsDpHRVMtK1lY3ksQhTcWn8F7j5fqbTPzhzfDRzu/+jDSzkkiN9B7C/sM2OXrT3u60YdTjSGJ79ohrDuTDiUv5cY7AubP7EJ9LGRsR65M8V5EX9RfYErxS810Q4jefcr+eI2xW9XeFG2zF1VUS1Cft8y9OgTf6y0dhVc84BHXT2jod44g2bdcdiNPoRGhdx7q9Z74oDBrYc3wn1gr+j7ExfDO1OjnUTrtfJU75CkaHpoUEaFx0YWg4wOt9VwVj9Y70DLP6xCFyOF+jQT5Y5IPoLEZGwdY1TD8= root@main"

- hosts: first
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: centos_family
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
