---

- hosts: first
  become: true
  pre_tasks: #run before anything else is run

  - name: update repo cache (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
  
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: all
  become: true
  roles:
    - workstations

- hosts: all
  become: true
  roles:
    - web_servers

- hosts: all
  become: true
  roles:
    - db_servers

- hosts: all
  become: true
  roles:
    - file_servers
